### ISSUE TITLE
Returning datetimes from GQL queries fails

### ISSUE THREAD

**Issue by pansapiens** [mytardis/edm-backend#18]
This GQL query fails and returns an HTML response: `Protocol.UndefinedError at POST /api/v1/graphql
protocol Calendar.ContainsDateTime not implemented for #Ecto.DateTime<2013-06-05 06:40:25>`

```
mutation {
	getOrCreateFile(input:{ clientMutationId: "bla",  
	                        source: {name: "test source"},
	                        file: {
	                          filepath: "testfile3.txt",
	                          size: 12
	                        }
	                        }) {
	    clientMutationId
	    file {
	    	filepath
	    	size
	    	mtime
	    }
	}
}
```

Setting mtime like `mtime: "2013-06-05T06:40:25.000Z"` in the input variables works fine.

**Comment by grischa** [comment]
http://www.creativedeletion.com/2016/02/04/timetypes_prevent_bugs.html
